# Generated by Django 5.1.6 on 2025-07-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_address_alter_order_total_cost_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
