# Generated by Django 5.1.6 on 2025-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_downloadablefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/%Y/%m/%d/', verbose_name='Файл для скачивания'),
        ),
    ]
